# Generated by Django 3.1.6 on 2021-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_topiccomment_tc_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutohomeData',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号id')),
                ('auto_brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('auto_series', models.CharField(blank=True, max_length=100, null=True, verbose_name='车系')),
                ('auto_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='类别')),
                ('auto_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='标签')),
                ('auto_evaluate', models.CharField(blank=True, max_length=10, null=True, verbose_name='正负面评估')),
                ('auto_text', models.CharField(blank=True, max_length=5000, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '汽车之家口碑',
                'verbose_name_plural': '汽车之家口碑',
            },
        ),
    ]
